name: CI/CD Pipeline for Fullstack App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Debug - List files in the root directory
      - name: Debug - List files in root
        run: ls -R

      # Debug - Show current working directory
      - name: Debug - Show current directory
        run: pwd

      - name: Debug - List files in working directory
        run: ls -R /home/runner/work/demo/demo

