name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js for frontend and backend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install backend dependencies
    - name: Install backend dependencies
      working-directory: TODO/todo_backend
      run: npm install

    # Run backend tests
    - name: Run backend tests
      working-directory: TODO/todo_backend
      run: npm test

    # Install frontend dependencies
    - name: Install frontend dependencies
      working-directory: TODO/todo_frontend
      run: npm install

    # Run frontend tests
    - name: Run frontend tests
      working-directory: TODO/todo_frontend
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production
      run: |
        echo "Deployment logic goes here"
