name: CI/CD Pipeline for Fullstack App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Debug - List files in the repository
      - name: Debug - List files
        run: ls -R /home/runner/work/demo/demo

      # Debug - Show current directory
      - name: Debug - Show current directory
        run: pwd

      # Step 2: Set up Node.js for Frontend
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Frontend Dependencies
      - name: Install dependencies (Frontend)
        working-directory: ./todo_frontend
        run: npm install

      # Step 4: Build Frontend
      - name: Build Frontend
        working-directory: ./todo_frontend
        run: npm run build

      # Step 5: Set up Node.js for Backend
      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 6: Install Backend Dependencies
      - name: Install dependencies (Backend)
        working-directory: ./todo_backend
        run: npm install
