name: CI/CD Pipeline for Fullstack App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Debug - List files in the repository
      - name: Debug - List files
        run: ls -R /home/runner/work/demo/demo
        
      - name: Debug - List contents of the current directory
        run: ls -d */
        
      - name: Install dependencies (Frontend)
        working-directory: /home/runner/work/demo/demo/TODO/todo_frontend
        run: npm install

      # Step 4: Build Frontend
      - name: Build Frontend
        working-directory: /home/runner/work/demo/demo/TODO/todo_frontend
        run: npm run build
        
# Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: /home/runner/work/demo/demo/TODO/todo_frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
