name: CI/CD Pipeline for Fullstack App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js for Frontend
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      # Debug - List files
      - name: Debug - List files
        run: ls -R /home/runner/work/demo/demo

      # Debug - Show current directory
      - name: Debug - Show current directory
        run: pwd

      # Step 3: Install dependencies (Frontend)
      - name: Install dependencies (Frontend)
        working-directory: /home/runner/work/demo/demo/TODO/todo_frontend
        run: npm install

      # Step 4: Build Frontend
      - name: Build Frontend
        working-directory: /home/runner/work/demo/demo/TODO/todo_frontend
        run: npm run build
        
      # Step 5: Install dependencies (Backend)
      - name: Install dependencies (Backend)
        working-directory: /home/runner/work/demo/demo/TODO/todo_backend
        run: npm install
        
      # Step 6: Setup Environment Variables for MongoDB
      - name: Setup Environment Variables
        run: |
          echo "MONGO_URI=mongodb://root:example@localhost:27017/TODO" >> $GITHUB_ENV

      # Step 7: Start Backend and Check if it's Ready
      - name: Start Backend
        working-directory: /home/runner/work/demo/demo/TODO/todo_backend
        run: |
          npm start & 
          sleep 10  # Increased sleep time for backend to start

      # Step 8: Run Backend Tests
      - name: Run Backend Tests
        working-directory: /home/runner/work/demo/demo/TODO/todo_backend
        run: npm test

      # Step 9: Install MongoDB Tools
      - name: Install MongoDB Tools
        run: sudo apt-get update && sudo apt-get install -y mongo-tools

      # Step 10: Verify Task in MongoDB
      - name: Check Task in MongoDB
        run: |
          mongosh --host localhost --eval "printjson(db.TODO.find().toArray())"

      # Step 11: Install Netlify CLI for Deployment
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 12: Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --prod --dir=/home/runner/work/demo/demo/TODO/todo_frontend/build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

      # Step 13: Save Task Locally (Optional step)
      - name: Save Task Locally
        run: |
          curl -X POST http://localhost:5000/add-task -d '{"task": "Sample task"}' -H "Content-Type: application/json"
          
      # Step 14: Verify Task Saved Locally
      - name: Verify Task Saved Locally
        run: |
          if [ -f /home/runner/work/demo/demo/TODO/todo_backend/tasks.txt ]; then
            echo "Task file exists and is not empty"
          else
            echo "Task file does not exist or is empty"
            exit 1
          fi
