name: CI/CD Pipeline for Fullstack App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js for Frontend
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      # Step 3: Install dependencies (Frontend)
      - name: Install dependencies (Frontend)
        working-directory: /home/runner/work/demo/demo/TODO/todo_frontend
        run: npm install

      # Step 4: Build Frontend
      - name: Build Frontend
        working-directory: /home/runner/work/demo/demo/TODO/todo_frontend
        run: npm run build
        
      # Step 5: Install dependencies (Backend)
      - name: Install dependencies (Backend)
        working-directory: /home/runner/work/demo/demo/TODO/todo_backend
        run: npm install
        
      # Step 6: Setup Environment Variables for MongoDB
      - name: Setup Environment Variables
        run: |
          echo "MONGO_URI=mongodb://root:example@localhost:27017/TODO" >> $GITHUB_ENV

      # Step 7: Start Backend
      - name: Start Backend
        working-directory: /home/runner/work/demo/demo/TODO/todo_backend
        run: npm start & sleep 5

      # Step 8: Run Backend Tests
      - name: Run Backend Tests
        working-directory: /home/runner/work/demo/demo/TODO/todo_backend
        run: npm test

      # Step 11: Verify Task in MongoDB
      - name: Check Task in MongoDB
        run: |
          sudo apt-get install -y mongodb-clients
          mongo --host localhost --eval "printjson(db.TODO.find().toArray())"

      # Step 12: Install Netlify CLI for Deployment
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 13: Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --prod --dir=/home/runner/work/demo/demo/TODO/todo_frontend/build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
