name: CI/CD Pipeline for Fullstack App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js for Frontend
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies (Frontend)
      - name: Install dependencies (Frontend)
        working-directory: home/runner/work/demo/demo/todo_frontend
        run: npm install

      # Step 4: Build Frontend
      - name: Build Frontend
        working-directory: home/runner/work/demo/demo/todo_frontend
        run: npm run build

      # Step 5: Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          curl -sL https://github.com/netlify/cli/releases/download/v10.1.0/netlify-cli-linux-amd64 > netlify-cli
          chmod +x netlify-cli
          mv netlify-cli /usr/local/bin/
          netlify deploy --prod --dir=todo_frontend/build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
