name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install backend dependencies
    - name: Install backend dependencies
      working-directory: TODO/todo_backend
      run: npm install

    # Step 4: Fix backend vulnerabilities
    - name: Fix backend vulnerabilities
      working-directory: TODO/todo_backend
      run: npm audit fix || true

    # Step 5: Run backend tests
    - name: Run backend tests
      working-directory: TODO/todo_backend
      run: npm test

    # Step 6: Install frontend dependencies
    - name: Install frontend dependencies
      working-directory: TODO/todo_frontend
      run: npm install

    # Step 7: Fix frontend vulnerabilities
    - name: Fix frontend vulnerabilities
      working-directory: TODO/todo_frontend
      run: npm audit fix || true

    # Step 8: Run frontend tests
    - name: Run frontend tests
      working-directory: TODO/todo_frontend
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 9: Deploy to production (Placeholder)
    - name: Deploy to Production
      run: |
        echo "Deployment logic goes here"
